// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pacts.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	pacts.proto

It has these top-level messages:
	Participant
	ParticipantVersion
	Pact
	PactPublication
	Tag
	PublishPactRequest
	GetParticipantsRequest
	Response
	PublishPactResponse
	GetAllProviderPactsRequest
	ConsumerInfo
	Links
	ParticipantResponse
	GetParticipantResponse
	GetParticipantsResponse
	GetParticipantVersionsResponse
	GetAllProviderPactsReponse
	GetProviderConsumerVersionPactRequest
	GetProviderConsumerVersionPactResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GetParticipantsRequest_ParticipantType int32

const (
	GetParticipantsRequest_ALL_PARTIES    GetParticipantsRequest_ParticipantType = 0
	GetParticipantsRequest_SINGLE_PARTY   GetParticipantsRequest_ParticipantType = 1
	GetParticipantsRequest_LATEST_PARTY   GetParticipantsRequest_ParticipantType = 2
	GetParticipantsRequest_VERSIONS_PARTY GetParticipantsRequest_ParticipantType = 3
)

var GetParticipantsRequest_ParticipantType_name = map[int32]string{
	0: "ALL_PARTIES",
	1: "SINGLE_PARTY",
	2: "LATEST_PARTY",
	3: "VERSIONS_PARTY",
}
var GetParticipantsRequest_ParticipantType_value = map[string]int32{
	"ALL_PARTIES":    0,
	"SINGLE_PARTY":   1,
	"LATEST_PARTY":   2,
	"VERSIONS_PARTY": 3,
}

func (x GetParticipantsRequest_ParticipantType) String() string {
	return proto1.EnumName(GetParticipantsRequest_ParticipantType_name, int32(x))
}
func (GetParticipantsRequest_ParticipantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

/*
type Response_Code int32

const (
	Response_UNKNOWN Response_Code = 0
	Response_SUCCESS Response_Code = 1
	Response_FAIL    Response_Code = 2
)

var Response_Code_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAIL",
}
var Response_Code_value = map[string]int32{
	"UNKNOWN": 0,
	"SUCCESS": 1,
	"FAIL":    2,
}

func (x Response_Code) String() string {
	return proto1.EnumName(Response_Code_name, int32(x))
}
func (Response_Code) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }
*/
type Participant struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AppId       string `protobuf:"bytes,2,opt,name=appId" json:"appId,omitempty"`
	ServiceName string `protobuf:"bytes,3,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *Participant) Reset()                    { *m = Participant{} }
func (m *Participant) String() string            { return proto1.CompactTextString(m) }
func (*Participant) ProtoMessage()               {}
func (*Participant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Participant) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Participant) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Participant) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type ParticipantVersion struct {
	Id            int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Number        string `protobuf:"bytes,2,opt,name=number" json:"number,omitempty"`
	ParticipantId int32  `protobuf:"varint,3,opt,name=participantId" json:"participantId,omitempty"`
	Order         int32  `protobuf:"varint,4,opt,name=order" json:"order,omitempty"`
}

func (m *ParticipantVersion) Reset()                    { *m = ParticipantVersion{} }
func (m *ParticipantVersion) String() string            { return proto1.CompactTextString(m) }
func (*ParticipantVersion) ProtoMessage()               {}
func (*ParticipantVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ParticipantVersion) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ParticipantVersion) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *ParticipantVersion) GetParticipantId() int32 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *ParticipantVersion) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

type Pact struct {
	Id                    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ConsumerParticipantId int32  `protobuf:"varint,2,opt,name=consumerParticipantId" json:"consumerParticipantId,omitempty"`
	ProviderParticipantId int32  `protobuf:"varint,3,opt,name=providerParticipantId" json:"providerParticipantId,omitempty"`
	Sha                   []byte `protobuf:"bytes,4,opt,name=sha,proto3" json:"sha,omitempty"`
	Content               []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Pact) Reset()                    { *m = Pact{} }
func (m *Pact) String() string            { return proto1.CompactTextString(m) }
func (*Pact) ProtoMessage()               {}
func (*Pact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Pact) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pact) GetConsumerParticipantId() int32 {
	if m != nil {
		return m.ConsumerParticipantId
	}
	return 0
}

func (m *Pact) GetProviderParticipantId() int32 {
	if m != nil {
		return m.ProviderParticipantId
	}
	return 0
}

func (m *Pact) GetSha() []byte {
	if m != nil {
		return m.Sha
	}
	return nil
}

func (m *Pact) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PactPublication struct {
	Id                   int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ParticipantVersionId int32 `protobuf:"varint,2,opt,name=participantVersionId" json:"participantVersionId,omitempty"`
	PactId               int32 `protobuf:"varint,3,opt,name=pactId" json:"pactId,omitempty"`
	ParticipantId        int32 `protobuf:"varint,4,opt,name=participantId" json:"participantId,omitempty"`
}

func (m *PactPublication) Reset()                    { *m = PactPublication{} }
func (m *PactPublication) String() string            { return proto1.CompactTextString(m) }
func (*PactPublication) ProtoMessage()               {}
func (*PactPublication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PactPublication) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PactPublication) GetParticipantVersionId() int32 {
	if m != nil {
		return m.ParticipantVersionId
	}
	return 0
}

func (m *PactPublication) GetPactId() int32 {
	if m != nil {
		return m.PactId
	}
	return 0
}

func (m *PactPublication) GetParticipantId() int32 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

type Tag struct {
	Name                 string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ParticipantVersionId int32  `protobuf:"varint,2,opt,name=participantVersionId" json:"participantVersionId,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto1.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetParticipantVersionId() int32 {
	if m != nil {
		return m.ParticipantVersionId
	}
	return 0
}

type PublishPactRequest struct {
	ProviderId string `protobuf:"bytes,1,opt,name=providerId" json:"providerId,omitempty"`
	ConsumerId string `protobuf:"bytes,2,opt,name=consumerId" json:"consumerId,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Pact       []byte `protobuf:"bytes,4,opt,name=pact,proto3" json:"pact,omitempty"`
}

func (m *PublishPactRequest) Reset()                    { *m = PublishPactRequest{} }
func (m *PublishPactRequest) String() string            { return proto1.CompactTextString(m) }
func (*PublishPactRequest) ProtoMessage()               {}
func (*PublishPactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PublishPactRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *PublishPactRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *PublishPactRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PublishPactRequest) GetPact() []byte {
	if m != nil {
		return m.Pact
	}
	return nil
}

type GetParticipantsRequest struct {
	PartyReqType  GetParticipantsRequest_ParticipantType `protobuf:"varint,1,opt,name=partyReqType,enum=com.huawei.paas.cse.serviceregistry.api.GetParticipantsRequest_ParticipantType" json:"partyReqType,omitempty"`
	ParticipantId string                                 `protobuf:"bytes,2,opt,name=participantId" json:"participantId,omitempty"`
	UrlPrefix     string                                 `protobuf:"bytes,3,opt,name=urlPrefix" json:"urlPrefix,omitempty"`
}

func (m *GetParticipantsRequest) Reset()                    { *m = GetParticipantsRequest{} }
func (m *GetParticipantsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetParticipantsRequest) ProtoMessage()               {}
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetParticipantsRequest) GetPartyReqType() GetParticipantsRequest_ParticipantType {
	if m != nil {
		return m.PartyReqType
	}
	return GetParticipantsRequest_ALL_PARTIES
}

func (m *GetParticipantsRequest) GetParticipantId() string {
	if m != nil {
		return m.ParticipantId
	}
	return ""
}

func (m *GetParticipantsRequest) GetUrlPrefix() string {
	if m != nil {
		return m.UrlPrefix
	}
	return ""
}

/*
type Response struct {
	Code    Response_Code `protobuf:"varint,1,opt,name=code,enum=com.huawei.paas.cse.serviceregistry.api.Response_Code" json:"code,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Response) GetCode() Response_Code {
	if m != nil {
		return m.Code
	}
	return Response_UNKNOWN
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}
*/
type PublishPactResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *PublishPactResponse) Reset()                    { *m = PublishPactResponse{} }
func (m *PublishPactResponse) String() string            { return proto1.CompactTextString(m) }
func (*PublishPactResponse) ProtoMessage()               {}
func (*PublishPactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PublishPactResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetAllProviderPactsRequest struct {
	ProviderId string `protobuf:"bytes,1,opt,name=providerId" json:"providerId,omitempty"`
}

func (m *GetAllProviderPactsRequest) Reset()                    { *m = GetAllProviderPactsRequest{} }
func (m *GetAllProviderPactsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetAllProviderPactsRequest) ProtoMessage()               {}
func (*GetAllProviderPactsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetAllProviderPactsRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

type ConsumerInfo struct {
	Href string `protobuf:"bytes,1,opt,name=href" json:"href,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ConsumerInfo) Reset()                    { *m = ConsumerInfo{} }
func (m *ConsumerInfo) String() string            { return proto1.CompactTextString(m) }
func (*ConsumerInfo) ProtoMessage()               {}
func (*ConsumerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ConsumerInfo) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *ConsumerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Links struct {
	Pacts []*ConsumerInfo `protobuf:"bytes,1,rep,name=pacts" json:"pacts,omitempty"`
}

func (m *Links) Reset()                    { *m = Links{} }
func (m *Links) String() string            { return proto1.CompactTextString(m) }
func (*Links) ProtoMessage()               {}
func (*Links) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Links) GetPacts() []*ConsumerInfo {
	if m != nil {
		return m.Pacts
	}
	return nil
}

type ParticipantResponse struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XLinks *Links `protobuf:"bytes,2,opt,name=_links,json=Links" json:"_links,omitempty"`
}

func (m *ParticipantResponse) Reset()                    { *m = ParticipantResponse{} }
func (m *ParticipantResponse) String() string            { return proto1.CompactTextString(m) }
func (*ParticipantResponse) ProtoMessage()               {}
func (*ParticipantResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ParticipantResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParticipantResponse) GetXLinks() *Links {
	if m != nil {
		return m.XLinks
	}
	return nil
}

type GetParticipantResponse struct {
	Response        *Response            `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	ParticipantInfo *ParticipantResponse `protobuf:"bytes,2,opt,name=participantInfo" json:"participantInfo,omitempty"`
}

func (m *GetParticipantResponse) Reset()                    { *m = GetParticipantResponse{} }
func (m *GetParticipantResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetParticipantResponse) ProtoMessage()               {}
func (*GetParticipantResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetParticipantResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetParticipantResponse) GetParticipantInfo() *ParticipantResponse {
	if m != nil {
		return m.ParticipantInfo
	}
	return nil
}

type GetParticipantsResponse struct {
	Response     *Response              `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	Participants []*ParticipantResponse `protobuf:"bytes,2,rep,name=participants" json:"participants,omitempty"`
}

func (m *GetParticipantsResponse) Reset()                    { *m = GetParticipantsResponse{} }
func (m *GetParticipantsResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetParticipantsResponse) ProtoMessage()               {}
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetParticipantsResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetParticipantsResponse) GetParticipants() []*ParticipantResponse {
	if m != nil {
		return m.Participants
	}
	return nil
}

type GetParticipantVersionsResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *GetParticipantVersionsResponse) Reset()                    { *m = GetParticipantVersionsResponse{} }
func (m *GetParticipantVersionsResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetParticipantVersionsResponse) ProtoMessage()               {}
func (*GetParticipantVersionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetParticipantVersionsResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetAllProviderPactsReponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	XLinks   *Links    `protobuf:"bytes,2,opt,name=_links,json=Links" json:"_links,omitempty"`
}

func (m *GetAllProviderPactsReponse) Reset()                    { *m = GetAllProviderPactsReponse{} }
func (m *GetAllProviderPactsReponse) String() string            { return proto1.CompactTextString(m) }
func (*GetAllProviderPactsReponse) ProtoMessage()               {}
func (*GetAllProviderPactsReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetAllProviderPactsReponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetAllProviderPactsReponse) GetXLinks() *Links {
	if m != nil {
		return m.XLinks
	}
	return nil
}

type GetProviderConsumerVersionPactRequest struct {
	ProviderId string `protobuf:"bytes,1,opt,name=providerId" json:"providerId,omitempty"`
	ConsumerId string `protobuf:"bytes,2,opt,name=consumerId" json:"consumerId,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *GetProviderConsumerVersionPactRequest) Reset()         { *m = GetProviderConsumerVersionPactRequest{} }
func (m *GetProviderConsumerVersionPactRequest) String() string { return proto1.CompactTextString(m) }
func (*GetProviderConsumerVersionPactRequest) ProtoMessage()    {}
func (*GetProviderConsumerVersionPactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17}
}

func (m *GetProviderConsumerVersionPactRequest) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *GetProviderConsumerVersionPactRequest) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *GetProviderConsumerVersionPactRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetProviderConsumerVersionPactResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	Pact     []byte    `protobuf:"bytes,2,opt,name=pact,proto3" json:"pact,omitempty"`
}

func (m *GetProviderConsumerVersionPactResponse) Reset() {
	*m = GetProviderConsumerVersionPactResponse{}
}
func (m *GetProviderConsumerVersionPactResponse) String() string { return proto1.CompactTextString(m) }
func (*GetProviderConsumerVersionPactResponse) ProtoMessage()    {}
func (*GetProviderConsumerVersionPactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18}
}

func (m *GetProviderConsumerVersionPactResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetProviderConsumerVersionPactResponse) GetPact() []byte {
	if m != nil {
		return m.Pact
	}
	return nil
}

func init() {
	proto1.RegisterType((*Participant)(nil), "com.huawei.paas.cse.serviceregistry.api.Participant")
	proto1.RegisterType((*ParticipantVersion)(nil), "com.huawei.paas.cse.serviceregistry.api.ParticipantVersion")
	proto1.RegisterType((*Pact)(nil), "com.huawei.paas.cse.serviceregistry.api.Pact")
	proto1.RegisterType((*PactPublication)(nil), "com.huawei.paas.cse.serviceregistry.api.PactPublication")
	proto1.RegisterType((*Tag)(nil), "com.huawei.paas.cse.serviceregistry.api.Tag")
	proto1.RegisterType((*PublishPactRequest)(nil), "com.huawei.paas.cse.serviceregistry.api.PublishPactRequest")
	proto1.RegisterType((*GetParticipantsRequest)(nil), "com.huawei.paas.cse.serviceregistry.api.GetParticipantsRequest")
	//proto1.RegisterType((*Response)(nil), "com.huawei.paas.cse.serviceregistry.api.Response")
	proto1.RegisterType((*PublishPactResponse)(nil), "com.huawei.paas.cse.serviceregistry.api.PublishPactResponse")
	proto1.RegisterType((*GetAllProviderPactsRequest)(nil), "com.huawei.paas.cse.serviceregistry.api.GetAllProviderPactsRequest")
	proto1.RegisterType((*ConsumerInfo)(nil), "com.huawei.paas.cse.serviceregistry.api.ConsumerInfo")
	proto1.RegisterType((*Links)(nil), "com.huawei.paas.cse.serviceregistry.api.Links")
	proto1.RegisterType((*ParticipantResponse)(nil), "com.huawei.paas.cse.serviceregistry.api.ParticipantResponse")
	proto1.RegisterType((*GetParticipantResponse)(nil), "com.huawei.paas.cse.serviceregistry.api.GetParticipantResponse")
	proto1.RegisterType((*GetParticipantsResponse)(nil), "com.huawei.paas.cse.serviceregistry.api.GetParticipantsResponse")
	proto1.RegisterType((*GetParticipantVersionsResponse)(nil), "com.huawei.paas.cse.serviceregistry.api.GetParticipantVersionsResponse")
	proto1.RegisterType((*GetAllProviderPactsReponse)(nil), "com.huawei.paas.cse.serviceregistry.api.GetAllProviderPactsReponse")
	proto1.RegisterType((*GetProviderConsumerVersionPactRequest)(nil), "com.huawei.paas.cse.serviceregistry.api.GetProviderConsumerVersionPactRequest")
	proto1.RegisterType((*GetProviderConsumerVersionPactResponse)(nil), "com.huawei.paas.cse.serviceregistry.api.GetProviderConsumerVersionPactResponse")
	proto1.RegisterEnum("com.huawei.paas.cse.serviceregistry.api.GetParticipantsRequest_ParticipantType", GetParticipantsRequest_ParticipantType_name, GetParticipantsRequest_ParticipantType_value)
	//proto1.RegisterEnum("com.huawei.paas.cse.serviceregistry.api.Response_Code", Response_Code_name, Response_Code_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BrokerServiceCtrl service

type BrokerServiceCtrlClient interface {
	PublishPact(ctx context.Context, in *PublishPactRequest, opts ...grpc.CallOption) (*PublishPactResponse, error)
	GetParticipant(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantResponse, error)
	GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error)
	GetParticipantVersions(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantVersionsResponse, error)
}

type brokerServiceCtrlClient struct {
	cc *grpc.ClientConn
}

func NewBrokerServiceCtrlClient(cc *grpc.ClientConn) BrokerServiceCtrlClient {
	return &brokerServiceCtrlClient{cc}
}

func (c *brokerServiceCtrlClient) PublishPact(ctx context.Context, in *PublishPactRequest, opts ...grpc.CallOption) (*PublishPactResponse, error) {
	out := new(PublishPactResponse)
	err := grpc.Invoke(ctx, "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/publishPact", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceCtrlClient) GetParticipant(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantResponse, error) {
	out := new(GetParticipantResponse)
	err := grpc.Invoke(ctx, "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/getParticipant", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceCtrlClient) GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantsResponse, error) {
	out := new(GetParticipantsResponse)
	err := grpc.Invoke(ctx, "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/getParticipants", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceCtrlClient) GetParticipantVersions(ctx context.Context, in *GetParticipantsRequest, opts ...grpc.CallOption) (*GetParticipantVersionsResponse, error) {
	out := new(GetParticipantVersionsResponse)
	err := grpc.Invoke(ctx, "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/getParticipantVersions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BrokerServiceCtrl service

type BrokerServiceCtrlServer interface {
	PublishPact(context.Context, *PublishPactRequest) (*PublishPactResponse, error)
	GetParticipant(context.Context, *GetParticipantsRequest) (*GetParticipantResponse, error)
	GetParticipants(context.Context, *GetParticipantsRequest) (*GetParticipantsResponse, error)
	GetParticipantVersions(context.Context, *GetParticipantsRequest) (*GetParticipantVersionsResponse, error)
}

func RegisterBrokerServiceCtrlServer(s *grpc.Server, srv BrokerServiceCtrlServer) {
	s.RegisterService(&_BrokerServiceCtrl_serviceDesc, srv)
}

func _BrokerServiceCtrl_PublishPact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceCtrlServer).PublishPact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/PublishPact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceCtrlServer).PublishPact(ctx, req.(*PublishPactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerServiceCtrl_GetParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceCtrlServer).GetParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/GetParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceCtrlServer).GetParticipant(ctx, req.(*GetParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerServiceCtrl_GetParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceCtrlServer).GetParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/GetParticipants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceCtrlServer).GetParticipants(ctx, req.(*GetParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerServiceCtrl_GetParticipantVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceCtrlServer).GetParticipantVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl/GetParticipantVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceCtrlServer).GetParticipantVersions(ctx, req.(*GetParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerServiceCtrl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.huawei.paas.cse.serviceregistry.api.BrokerServiceCtrl",
	HandlerType: (*BrokerServiceCtrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "publishPact",
			Handler:    _BrokerServiceCtrl_PublishPact_Handler,
		},
		{
			MethodName: "getParticipant",
			Handler:    _BrokerServiceCtrl_GetParticipant_Handler,
		},
		{
			MethodName: "getParticipants",
			Handler:    _BrokerServiceCtrl_GetParticipants_Handler,
		},
		{
			MethodName: "getParticipantVersions",
			Handler:    _BrokerServiceCtrl_GetParticipantVersions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pacts.proto",
}

func init() { proto1.RegisterFile("pacts.proto", fileDescriptor0) }

/*
var fileDescriptor0 = []byte{
	// 911 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xdf, 0x71, 0x9c, 0x6e, 0xf7, 0xb9, 0xb4, 0x61, 0x76, 0x29, 0x56, 0x85, 0x56, 0xd5, 0x88,
	0x3f, 0x15, 0x07, 0x0b, 0x02, 0xec, 0x85, 0x4a, 0x90, 0x8d, 0x42, 0x15, 0x36, 0x9b, 0x46, 0x76,
	0xba, 0x88, 0xbd, 0x2c, 0xae, 0x3d, 0x49, 0xad, 0x4d, 0x6c, 0xef, 0x8c, 0x53, 0xb6, 0x47, 0x38,
	0x21, 0x71, 0x03, 0x8e, 0x9c, 0xb8, 0xc3, 0x81, 0x8f, 0xc1, 0x85, 0x8f, 0xc2, 0x57, 0x40, 0x33,
	0x1e, 0x3b, 0x76, 0x62, 0xd4, 0x90, 0x12, 0x4e, 0x9d, 0xf7, 0x26, 0xf3, 0x7b, 0xbf, 0xf7, 0xde,
	0xef, 0xcd, 0xd4, 0x60, 0xc4, 0xae, 0x97, 0x70, 0x2b, 0x66, 0x51, 0x12, 0xe1, 0x77, 0xbc, 0x68,
	0x6a, 0x5d, 0xcc, 0xdc, 0xaf, 0x69, 0x60, 0xc5, 0xae, 0xcb, 0x2d, 0x8f, 0x53, 0x8b, 0x53, 0x76,
	0x19, 0x78, 0x94, 0xd1, 0x71, 0xc0, 0x13, 0x76, 0x65, 0xb9, 0x71, 0x40, 0xce, 0xc0, 0x18, 0xb8,
	0x2c, 0x09, 0xbc, 0x20, 0x76, 0xc3, 0x04, 0xef, 0x82, 0x16, 0xf8, 0x26, 0x3a, 0x44, 0x47, 0x75,
	0x5b, 0x0b, 0x7c, 0x7c, 0x0f, 0xea, 0x6e, 0x1c, 0x77, 0x7d, 0x53, 0x3b, 0x44, 0x47, 0x77, 0xec,
	0xd4, 0xc0, 0x87, 0x60, 0x28, 0xac, 0xbe, 0x3b, 0xa5, 0x66, 0x4d, 0xee, 0x15, 0x5d, 0xe4, 0x25,
	0xe0, 0x02, 0xec, 0x13, 0xca, 0x78, 0x10, 0x85, 0x4b, 0xe8, 0xfb, 0xb0, 0x15, 0xce, 0xa6, 0xe7,
	0x94, 0x29, 0x78, 0x65, 0xe1, 0x37, 0xe1, 0x95, 0x78, 0x7e, 0xba, 0xeb, 0xcb, 0x08, 0x75, 0xbb,
	0xec, 0x14, 0xdc, 0x22, 0xe6, 0x53, 0x66, 0xea, 0x72, 0x37, 0x35, 0xc8, 0x6f, 0x08, 0xf4, 0x81,
	0xeb, 0x2d, 0xa7, 0xf2, 0x21, 0xbc, 0xe6, 0x45, 0x21, 0x9f, 0x4d, 0x29, 0x1b, 0x94, 0xc0, 0x35,
	0xf9, 0x93, 0xea, 0x4d, 0x71, 0x2a, 0x66, 0xd1, 0x65, 0xe0, 0x2f, 0x9e, 0x4a, 0x29, 0x55, 0x6f,
	0xe2, 0x06, 0xd4, 0xf8, 0x85, 0x2b, 0x89, 0xed, 0xd8, 0x62, 0x89, 0x4d, 0xb8, 0xed, 0x45, 0x61,
	0x42, 0xc3, 0xc4, 0xac, 0x4b, 0x6f, 0x66, 0x92, 0x1f, 0x11, 0xec, 0x09, 0xc2, 0x83, 0xd9, 0xf9,
	0x24, 0xf0, 0xdc, 0xa4, 0xaa, 0x50, 0x4d, 0xb8, 0x17, 0x2f, 0x95, 0x33, 0xa7, 0x5e, 0xb9, 0x27,
	0x8a, 0x2b, 0x14, 0x91, 0x53, 0x55, 0xd6, 0x72, 0x71, 0xf5, 0x8a, 0xe2, 0x92, 0xc7, 0x50, 0x1b,
	0xba, 0x63, 0x8c, 0x41, 0x0f, 0x45, 0x8b, 0x91, 0xec, 0x8f, 0x5c, 0xaf, 0x43, 0x86, 0x7c, 0x8b,
	0x00, 0xcb, 0x04, 0xf9, 0x85, 0xc8, 0xd5, 0xa6, 0x2f, 0x66, 0x94, 0x27, 0xf8, 0x3e, 0x40, 0x56,
	0xc0, 0xae, 0xaf, 0x82, 0x14, 0x3c, 0x62, 0x3f, 0x6b, 0x4b, 0xae, 0xc1, 0x82, 0x47, 0x54, 0xf5,
	0x32, 0x8d, 0xa1, 0x44, 0x98, 0x99, 0x82, 0xb8, 0xc8, 0x57, 0xb5, 0x40, 0xae, 0xc9, 0xaf, 0x1a,
	0xec, 0x9f, 0xd0, 0xa4, 0xd0, 0x2a, 0x9e, 0x11, 0xe1, 0xb0, 0x23, 0x78, 0x5f, 0xd9, 0xf4, 0xc5,
	0xf0, 0x2a, 0x4e, 0xf3, 0xdd, 0x6d, 0x9e, 0x5a, 0x2b, 0x8e, 0x91, 0x55, 0x0d, 0x6b, 0x15, 0x7c,
	0x02, 0xd6, 0x2e, 0x05, 0x59, 0xee, 0x44, 0x9a, 0xe0, 0x82, 0xcc, 0xdf, 0x80, 0x3b, 0x33, 0x36,
	0x19, 0x30, 0x3a, 0x0a, 0x5e, 0xaa, 0x2c, 0xe7, 0x0e, 0xf2, 0x54, 0x88, 0xa7, 0x14, 0x04, 0xef,
	0x81, 0xd1, 0xea, 0xf5, 0x9e, 0x0d, 0x5a, 0xf6, 0xb0, 0xdb, 0x71, 0x1a, 0xb7, 0x70, 0x03, 0x76,
	0x9c, 0x6e, 0xff, 0xa4, 0xd7, 0x91, 0xbe, 0x2f, 0x1b, 0x48, 0x78, 0x7a, 0xad, 0x61, 0xc7, 0x19,
	0x2a, 0x8f, 0x86, 0x31, 0xec, 0x3e, 0xe9, 0xd8, 0x4e, 0xf7, 0xb4, 0xef, 0x28, 0x5f, 0x8d, 0xfc,
	0x8c, 0x60, 0xdb, 0xa6, 0x3c, 0x8e, 0x42, 0x4e, 0xf1, 0xe7, 0xa0, 0x7b, 0x91, 0x9f, 0x55, 0xe6,
	0xc1, 0xca, 0x95, 0xc9, 0x00, 0xac, 0x76, 0xe4, 0x53, 0x5b, 0x62, 0x88, 0xb6, 0x4d, 0x29, 0xe7,
	0xee, 0x98, 0xaa, 0x94, 0x33, 0x93, 0xbc, 0x0b, 0xba, 0xf8, 0x1d, 0x36, 0xe0, 0xf6, 0x59, 0xff,
	0x51, 0xff, 0xf4, 0x8b, 0x7e, 0xe3, 0x96, 0x30, 0x9c, 0xb3, 0x76, 0xbb, 0xe3, 0x38, 0x0d, 0x84,
	0xb7, 0x41, 0xff, 0xac, 0xd5, 0xed, 0x35, 0x34, 0xe2, 0xc3, 0xdd, 0x92, 0xa4, 0x14, 0xd1, 0xc7,
	0xb0, 0xcd, 0xd4, 0x5a, 0x92, 0x35, 0x9a, 0xef, 0xff, 0x6b, 0xb2, 0x76, 0x0e, 0x41, 0x8e, 0xe1,
	0xe0, 0x84, 0x26, 0xad, 0xc9, 0x64, 0x90, 0x4f, 0xba, 0x37, 0xd7, 0xcd, 0x35, 0x02, 0x26, 0x0f,
	0x60, 0xa7, 0x9d, 0xc9, 0x35, 0x1c, 0x45, 0x42, 0x96, 0x17, 0x8c, 0x8e, 0xb2, 0x79, 0x12, 0xeb,
	0x7c, 0xc6, 0xb4, 0xf9, 0x8c, 0x91, 0x21, 0xd4, 0x7b, 0x41, 0xf8, 0x9c, 0xe3, 0x47, 0x50, 0x97,
	0xf7, 0xba, 0x89, 0x0e, 0x6b, 0x47, 0x46, 0xf3, 0xa3, 0x95, 0x53, 0x29, 0x86, 0xb5, 0x53, 0x0c,
	0x12, 0xc3, 0xdd, 0x82, 0x58, 0xf2, 0x8a, 0x55, 0x0d, 0x79, 0x07, 0xb6, 0x9e, 0x4d, 0x04, 0x03,
	0x49, 0xcb, 0x68, 0x5a, 0x2b, 0x07, 0x96, 0xbc, 0xed, 0x94, 0x3e, 0xf9, 0x13, 0x2d, 0x8e, 0xdc,
	0x86, 0xfa, 0x84, 0x47, 0xb0, 0x57, 0x9c, 0x9b, 0x70, 0x14, 0x29, 0xe6, 0xc7, 0x2b, 0xa3, 0x56,
	0xb0, 0xb4, 0x17, 0x41, 0xc9, 0x1f, 0x08, 0x5e, 0x5f, 0x9a, 0xf6, 0xcd, 0xa4, 0xf4, 0x55, 0x7a,
	0x29, 0x65, 0x61, 0x4c, 0x4d, 0x4a, 0xe0, 0x66, 0xf9, 0x94, 0x10, 0x49, 0x04, 0xf7, 0xcb, 0xb9,
	0xa8, 0x1b, 0x7b, 0x53, 0x29, 0x91, 0xdf, 0xd1, 0x3f, 0x8c, 0xd3, 0x46, 0x0a, 0xf8, 0x1f, 0x89,
	0xf8, 0x1b, 0x04, 0x6f, 0x89, 0x32, 0x29, 0xc6, 0xd9, 0x64, 0xa9, 0x5a, 0xfd, 0x2f, 0xef, 0x19,
	0xf9, 0x1e, 0xc1, 0xdb, 0xd7, 0x71, 0xd8, 0x8c, 0x0a, 0xb3, 0x97, 0x54, 0x9b, 0xbf, 0xa4, 0xcd,
	0xbf, 0x74, 0x78, 0xf5, 0x21, 0x8b, 0x9e, 0x53, 0xe6, 0xa4, 0x20, 0xed, 0x84, 0x4d, 0xf0, 0x77,
	0x08, 0x8c, 0x78, 0x7e, 0x23, 0xe3, 0x8f, 0x57, 0x57, 0xea, 0xd2, 0xbf, 0x06, 0x07, 0xc7, 0xeb,
	0x1d, 0x56, 0xa4, 0x7f, 0x40, 0xb0, 0x3b, 0x2e, 0x29, 0x1b, 0x7f, 0x72, 0xc3, 0xc7, 0xfc, 0x60,
	0x5d, 0x80, 0x9c, 0xd4, 0x4f, 0x08, 0xf6, 0xca, 0xa4, 0xf8, 0xcd, 0x59, 0x7d, 0xba, 0x3e, 0x80,
	0xa2, 0xf5, 0x0b, 0x82, 0xfd, 0x71, 0xe5, 0x2d, 0x70, 0x73, 0x76, 0x27, 0x6b, 0x02, 0x2c, 0xde,
	0x43, 0x0f, 0xdf, 0x83, 0x55, 0x3f, 0x69, 0x9e, 0xd6, 0xe5, 0x27, 0xd0, 0xf9, 0x96, 0xfc, 0xf3,
	0xc1, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x79, 0xed, 0x40, 0x74, 0x18, 0x0d, 0x00, 0x00,
}
*/
